### ISSUE TITLE
Initial Project

### ISSUE THREAD

**Issue by mildminihi** [it-kmitl-2018/group5#4]
Initial with Kotlin module for JavaScript on IntelliJ IDEA

**Comment by champillon** [comment]
Kotlin เป็นภาษา
JavaScript ก็เป็น ภาษา
เราเลยงงว่า Kotlin module for JavaScript นี่ คือ module ภาษา Kotlin สำหรับภาษา JavaScript รึป่าวครับ

**Comment by mildminihi** [comment]
ใช่ครับ

**Comment by champillon** [comment]
อันนี้คือ อันนี้มใช้รึป่าวครับ => https://kotlinlang.org/docs/tutorials/javascript/kotlin-to-javascript/kotlin-to-javascript.html

**Comment by mildminihi** [comment]
ใช่ครับผม
